Вопросы 8-14
pfrankov/winterview-courses pull request #11
Opened 2020-09-15 11:18 UTC by LeraGreen

2020-09-21 00:55 UTC, pfrankov requested changes
`getFinalText(state.answers, 7)`
Здесь вопросов всё ещё 7

2020-09-21 00:55 UTC, pfrankov commented on src/courses/data-structures/data-structures.ts
> +      сontent: {
Здесь кириллическая С вместо C

2020-09-21 08:33 UTC, LeraGreen commented on src/courses/data-structures/data-structures.ts
> +      сontent: {
Поправила, запушила ⬇️

2020-09-22 19:17 UTC, pfrankov approved these changes

2020-09-22 19:17 UTC, merged